###
GET http://localhost:8081/api/habits
Authorization: Bearer {{$auth.token("habit")}}

###
GET http://localhost:8081/api/habits/1
Authorization: Bearer {{$auth.token("habit")}}

###
POST http://localhost:8081/api/habits
Content-Type: application/json
Authorization: Bearer {{$auth.token("habit")}}

{
  "name": "Read a book",
  "description": "Read at least 20 pages of a book every day",
  "schedule": "daily"
}

###
PUT http://localhost:8081/api/habits/1
Content-Type: application/json
Authorization: Bearer {{$auth.token("habit")}}

{
  "name": "Read a book",
  "description": "Read at least 30 pages of a book every day",
  "schedule": "daily"
}

###
DELETE http://localhost:8081/api/habits/1
Authorization: Bearer {{$auth.token("habit")}}