import "./globals.css";
import { KeycloakProvider } from "@/ui/KeycloakProvider";
import { NavBar } from "@/ui/NavBar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <KeycloakProvider>
        <NavBar />
        {children}
      </KeycloakProvider>
      </body>
    </html>
  );
}
