import "./globals.css";
import { KeycloakProvider } from "@/ui/KeycloakProvider";
import { NavBar } from "@/ui/NavBar";
import { Container } from "react-bootstrap";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <NavBar />
      <Container>
          <KeycloakProvider>
            {children}
          </KeycloakProvider>
        </Container>
      </body>
    </html>
  );
}
