###
GET http://localhost:8888/admin/realms/habit-realm/users
Content-Type: application/json
Authorization: Bearer {{$auth.token("habit")}}

###
GET http://localhost:8888/admin/realms/habit-realm/users/c25bab39-814d-4c44-a861-90360ffb88ca
Content-Type: application/json
Authorization: Bearer {{$auth.token("habit")}}

###
POST http://localhost:8888/realms/habit-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = habit-frontend &
username = buben &
password = buben

###
GET http://localhost:8888/realms/habit-realm

###
GET http://localhost:8888/realms/habit-realm/.well-known/openid-configuration

###
GET http://localhost:8888/realms/habit-realm/protocol/openid-connect/certs