spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/habit-realm
server:
  port: 8082
