eureka:
  instance:
    hostname: localhost
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkindb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.add.type.headers: true
        spring.json.trusted.packages: "cz.buben.learning.habits.common.dto"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/habit-realm
  threads:
    virtual:
      enabled: true

server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  health:
    eureka:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /checkin-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /checkin-service/swagger-ui.html
  oauth:
    client-id: swagger-ui
    client-secret: justFillerBecausePKCEisUsed
    use-pkce-with-authorization-code-grant: true
  oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
