eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: habit-service
              uri: lb://habit-service
              predicates:
                - Path=/api/habits/**
            - id: checkin-service
              uri: lb://checkin-service
              predicates:
                - Path=/api/checkins/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - AddResponseHeader=X-Gateway, HabitGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/habit-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  health:
    eureka:
      enabled: true
