eureka:
  instance:
    hostname: localhost
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    registryFetchIntervalSeconds: 5

server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      cache:
        ttl: 5s                       # or even disable cache in dev:
        # enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: habit-service
              uri: lb://habit-service
              predicates:
                - Path=/api/habits/**
            - id: checkin-service
              uri: lb://checkin-service
              predicates:
                - Path=/api/checkins/**
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        default-filters:
          - name: Retry
            args:
              retries: 3
              methods: GET
              statuses:
                - SERVICE_UNAVAILABLE      # 503
                - GATEWAY_TIMEOUT          # 504
                - BAD_GATEWAY              # 502
              exceptions:
                - java.io.IOException      # connection reset, etc.
                - org.springframework.cloud.gateway.support.TimeoutException
                - org.apache.hc.client5.http.HttpHostConnectException
              backoff:
                firstBackoff: 200ms
                maxBackoff: 2s
                factor: 2
                basedOnPreviousValue: true
          - AddResponseHeader=X-Gateway, HabitGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/habit-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  health:
    eureka:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
